---
framework: jest
postMerge:
  env:
    TRACE_PLAYWRIGHT: true
    HEADLESS: true
  pattern:
    - 'test/unit/**/*.test.{js,ts,tsx}'
preMerge:
  env:
    TRACE_PLAYWRIGHT: true
    HEADLESS: true
  pattern:
    - 'test/unit/**/*.test.{js,ts,tsx}'
preRun:
  command:
    - yarn
postRun:
  command:
    - node --version
version: 2.1
